server:
  port: 8081

spring:
  application:
    name: patients-service

  datasource:
    url: jdbc:mysql://localhost:3306/patients-db?createDatabaseIfNotExist=true
    username: root
    password: root      # si tu as un mot de passe, mets-le ici
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
