server:
  port: 8084

spring:
  application:
    name: appointments-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3309/hospital_appointments?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: hospital
    password: hospital
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect: inutile (Hibernate détecte)

  batch:
    jdbc:
      initialize-schema: always   # crée les tables BATCH_*
    job:
      enabled: false              # pas de lancement auto au démarrage
