server:
  port: 8088

spring:
  application:
    name: patients-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/hospital_patients?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: hospital
    password: hospital
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # retire dialect (optionnel) : Hibernate le détecte tout seul

management:
  endpoints:
    web:
      exposure:
        include: "*"
